name: Copy Folder from Another Repository

on:
  workflow_dispatch:

jobs:
  copy-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: round123/BAALAM_android_kernel_xiaomi_sm8250
          path: source-repo
          ref: upstream

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: round123/KernelPatch
          path: target-repo

      - name: Copy files
        run: |
          cp -R source-repo/include/linux/* target-repo/kernel/include/linux/

      - name: Push changes
        run: |
          cd target-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add kernel/include/linux/
          git commit -m "Copy linux folder from source repository"
          git push
